name: Hexo pages

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: false  # 禁用子模块检查

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: 安装依赖
        run: npm install

      - name: 安装hexo
        run: |
          npm install hexo-deployer-git --save
          npm install hexo-cli -g
          npm install --save hexo-blog-encrypt
          npm install hexo-renderer-pug hexo-renderer-stylus
          npm install hexo-generator-search --save
      - name: 创建blog页面
        run: |
          git clone https://github.com/wyxdlz54188/butterfly.git themes/butterfly
          hexo clean
          hexo generate
          ls

      - name: 设置Git配置
        run: |
          git config --global user.name 'wuyizhen-me'
          git config --global user.email 'wuyizhen2023@163.com'

      - name: 上传GitHub pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          ls
          cd public
          git init
          git add .
          git commit -m "Create by workflows"
          git remote add origin https://${{ secrets.GH_TOKEN }}@github.com/wuyizhen-me/blog.git
          git push origin HEAD:gh-pages -f

